// RBAC seed data — roles, permissions, and role-permission assignments.
// No Prisma enum dependencies; all values are plain strings.

export const SYSTEM_ROLES = [
  { code: "SUPER_ADMIN", name: "Super Admin", description: "Full access to all modules and actions" },
  { code: "ACADEMY_ADMIN", name: "Academy Admin", description: "Manage learners, courses, programs, batches, trainers, assessments" },
  { code: "TRAINER", name: "Trainer", description: "Schedule, attendance, assessments within assigned context" },
  { code: "CONTENT_MANAGER", name: "Content Manager", description: "Courses, programs, LMS, email templates" },
  { code: "SUPPORT_USER", name: "Support User", description: "Support tickets, learner view-only" },
  { code: "CANDIDATE", name: "Candidate", description: "Candidate app access (no admin portal permissions)" },
];

export const PERMISSION_DEFINITIONS = [
  { module: "dashboard", action: "view", key: "dashboard.view", description: "View dashboard" },
  { module: "users", action: "view", key: "users.view", description: "View learners/users" },
  { module: "users", action: "create", key: "users.create", description: "Create learners/users" },
  { module: "users", action: "edit", key: "users.edit", description: "Edit learners/users" },
  { module: "users", action: "delete", key: "users.delete", description: "Delete learners/users" },
  { module: "staff_users", action: "view", key: "staff_users.view", description: "View internal users" },
  { module: "staff_users", action: "create", key: "staff_users.create", description: "Create internal users" },
  { module: "staff_users", action: "edit", key: "staff_users.edit", description: "Edit internal users" },
  { module: "staff_users", action: "delete", key: "staff_users.delete", description: "Deactivate internal users" },
  { module: "candidate_users", action: "view", key: "candidate_users.view", description: "View candidate users" },
  { module: "candidate_users", action: "create", key: "candidate_users.create", description: "Onboard candidate users" },
  { module: "candidate_users", action: "edit", key: "candidate_users.edit", description: "Edit candidate users" },
  { module: "candidate_users", action: "delete", key: "candidate_users.delete", description: "Deactivate candidate users" },
  { module: "notifications", action: "view", key: "notifications.view", description: "View push notification readiness and delivery history" },
  { module: "notifications", action: "send", key: "notifications.send", description: "Send push notifications to candidates and batches" },
  { module: "auth", action: "login", key: "auth.login", description: "Sign in to the academy admin portal" },
  { module: "auth", action: "manage", key: "auth.manage", description: "Manage authentication and account recovery" },
  { module: "sessions", action: "view", key: "sessions.view", description: "View active sessions" },
  { module: "sessions", action: "manage", key: "sessions.manage", description: "Manage active sessions and logout all devices" },
  { module: "courses", action: "view", key: "courses.view", description: "View courses" },
  { module: "courses", action: "create", key: "courses.create", description: "Create courses" },
  { module: "courses", action: "edit", key: "courses.edit", description: "Edit courses" },
  { module: "courses", action: "delete", key: "courses.delete", description: "Delete courses" },
  { module: "programs", action: "view", key: "programs.view", description: "View programs" },
  { module: "programs", action: "create", key: "programs.create", description: "Create programs" },
  { module: "programs", action: "edit", key: "programs.edit", description: "Edit programs" },
  { module: "programs", action: "delete", key: "programs.delete", description: "Delete programs" },
  { module: "batches", action: "view", key: "batches.view", description: "View batches" },
  { module: "batches", action: "create", key: "batches.create", description: "Create batches" },
  { module: "batches", action: "edit", key: "batches.edit", description: "Edit batches" },
  { module: "batches", action: "delete", key: "batches.delete", description: "Delete batches" },
  { module: "centers", action: "view", key: "centers.view", description: "View physical centers" },
  { module: "centers", action: "create", key: "centers.create", description: "Create physical centers" },
  { module: "centers", action: "edit", key: "centers.edit", description: "Edit physical centers" },
  { module: "centers", action: "delete", key: "centers.delete", description: "Archive physical centers" },
  { module: "trainers", action: "view", key: "trainers.view", description: "View trainers" },
  { module: "trainers", action: "create", key: "trainers.create", description: "Create trainers" },
  { module: "trainers", action: "edit", key: "trainers.edit", description: "Edit trainers" },
  { module: "trainers", action: "assign", key: "trainers.assign", description: "Assign trainers to courses and assessments" },
  { module: "trainers", action: "delete", key: "trainers.delete", description: "Archive trainers" },
  { module: "trainers", action: "manage", key: "trainers.manage", description: "Manage trainer assignments" },
  { module: "trainers", action: "status.manage", key: "trainers.status.manage", description: "Manage trainer status (activate, deactivate, suspend)" },
  { module: "schedule", action: "view", key: "schedule.view", description: "View schedule" },
  { module: "schedule", action: "create", key: "schedule.create", description: "Create schedule events" },
  { module: "schedule", action: "edit", key: "schedule.edit", description: "Edit schedule events" },
  { module: "schedule", action: "delete", key: "schedule.delete", description: "Delete schedule events" },
  { module: "attendance", action: "view", key: "attendance.view", description: "View attendance" },
  { module: "attendance", action: "manage", key: "attendance.manage", description: "Mark/manage attendance" },
  { module: "assessments", action: "view", key: "assessments.view", description: "View assessments" },
  { module: "assessments", action: "create", key: "assessments.create", description: "Create assessments" },
  { module: "assessments", action: "edit", key: "assessments.edit", description: "Edit assessments" },
  { module: "assessments", action: "delete", key: "assessments.delete", description: "Delete assessments" },
  { module: "assessments", action: "publish", key: "assessments.publish", description: "Publish assessments" },
  { module: "certifications", action: "view", key: "certifications.view", description: "View certifications" },
  { module: "certifications", action: "create", key: "certifications.create", description: "Create certifications" },
  { module: "certifications", action: "edit", key: "certifications.edit", description: "Edit certifications" },
  { module: "certifications", action: "delete", key: "certifications.delete", description: "Delete certifications" },
  { module: "readiness", action: "view", key: "readiness.view", description: "View readiness" },
  { module: "readiness", action: "manage", key: "readiness.manage", description: "Manage readiness/sync" },
  { module: "lms", action: "view", key: "lms.view", description: "View LMS content" },
  { module: "lms", action: "create", key: "lms.create", description: "Create LMS content" },
  { module: "lms", action: "edit", key: "lms.edit", description: "Edit LMS content" },
  { module: "lms", action: "manage", key: "lms.manage", description: "Manage LMS settings" },
  { module: "quizzes", action: "view", key: "quizzes.view", description: "View quizzes" },
  { module: "quizzes", action: "create", key: "quizzes.create", description: "Create quizzes" },
  { module: "quizzes", action: "edit", key: "quizzes.edit", description: "Edit quizzes" },
  { module: "quizzes", action: "delete", key: "quizzes.delete", description: "Delete quizzes" },
  { module: "quizzes", action: "publish", key: "quizzes.publish", description: "Publish quizzes" },
  { module: "payments", action: "view", key: "payments.view", description: "View payments" },
  { module: "payments", action: "manage", key: "payments.manage", description: "Manage payments" },
  { module: "support", action: "view", key: "support.view", description: "View support tickets" },
  { module: "support", action: "manage", key: "support.manage", description: "Manage support tickets" },
  { module: "logs", action: "view", key: "logs.view", description: "View logs and actions" },
  { module: "settings", action: "view", key: "settings.view", description: "View settings" },
  { module: "settings", action: "edit", key: "settings.edit", description: "Edit settings" },
  { module: "settings", action: "manage", key: "settings.manage", description: "Manage settings categories and fields" },
  { module: "email_templates", action: "view", key: "email_templates.view", description: "View email templates" },
  { module: "email_templates", action: "create", key: "email_templates.create", description: "Create email templates" },
  { module: "email_templates", action: "edit", key: "email_templates.edit", description: "Edit email templates" },
  { module: "email_templates", action: "delete", key: "email_templates.delete", description: "Delete email templates" },
  { module: "roles", action: "view", key: "roles.view", description: "View roles and permissions" },
  { module: "roles", action: "create", key: "roles.create", description: "Create roles" },
  { module: "roles", action: "edit", key: "roles.edit", description: "Edit roles and permission assignments" },
  { module: "roles", action: "delete", key: "roles.delete", description: "Delete roles" },
  { module: "course_content", action: "view", key: "course_content.view", description: "View course content" },
  { module: "course_content", action: "create", key: "course_content.create", description: "Upload course content" },
  { module: "course_content", action: "edit", key: "course_content.edit", description: "Edit course content" },
  { module: "course_content", action: "delete", key: "course_content.delete", description: "Delete course content" },
  { module: "learning_resources", action: "view", key: "learning_resources.view", description: "View learning resources" },
  { module: "learning_resources", action: "create", key: "learning_resources.create", description: "Create learning resources" },
  { module: "learning_resources", action: "edit", key: "learning_resources.edit", description: "Edit learning resources" },
  { module: "learning_resources", action: "delete", key: "learning_resources.delete", description: "Delete learning resources" },
  { module: "learning_resources", action: "assign", key: "learning_resources.assign", description: "Assign learning resources" },
  { module: "course_content_folder", action: "view", key: "course_content_folder.view", description: "View course content folders" },
  { module: "course_content_folder", action: "create", key: "course_content_folder.create", description: "Create course content folders" },
  { module: "course_content_folder", action: "edit", key: "course_content_folder.edit", description: "Edit course content folders" },
  { module: "course_content_folder", action: "delete", key: "course_content_folder.delete", description: "Delete course content folders" },
  { module: "assessment_pool", action: "view", key: "assessment_pool.view", description: "View assessment pool" },
  { module: "assessment_pool", action: "create", key: "assessment_pool.create", description: "Create assessments in pool" },
  { module: "assessment_pool", action: "edit", key: "assessment_pool.edit", description: "Edit assessment pool items" },
  { module: "assessment_pool", action: "delete", key: "assessment_pool.delete", description: "Delete assessment pool items" },
  { module: "assessment_pool", action: "publish", key: "assessment_pool.publish", description: "Publish assessment pool items" },
  { module: "assessment_reviews", action: "view", key: "assessment_reviews.view", description: "View assessment review queue" },
  { module: "assessment_reviews", action: "manage", key: "assessment_reviews.manage", description: "Manage assessment review attempts" },
  { module: "assessment_reviews", action: "grade", key: "assessment_reviews.grade", description: "Manual grade assessment attempts" },
  { module: "batch_content", action: "view", key: "batch_content.view", description: "View batch content mappings" },
  { module: "batch_content", action: "assign", key: "batch_content.assign", description: "Assign content to batches" },
  { module: "batch_content", action: "remove", key: "batch_content.remove", description: "Remove content from batches" },
  { module: "curriculum", action: "view", key: "curriculum.view", description: "View curricula" },
  { module: "curriculum", action: "create", key: "curriculum.create", description: "Create curricula" },
  { module: "curriculum", action: "edit", key: "curriculum.edit", description: "Edit curricula" },
  { module: "curriculum", action: "delete", key: "curriculum.delete", description: "Delete curricula" },
  { module: "curriculum", action: "publish", key: "curriculum.publish", description: "Publish curricula" },
];

// SUPER_ADMIN gets implicit bypass in code — no explicit permissions needed.
// CANDIDATE gets no admin portal permissions.
export const ROLE_PERMISSION_MAP = {
  ACADEMY_ADMIN: [
    "dashboard.view",
    "auth.login", "auth.manage",
    "sessions.view", "sessions.manage",
    "users.view", "users.create", "users.edit", "users.delete",
    "staff_users.view", "staff_users.create", "staff_users.edit", "staff_users.delete",
    "candidate_users.view", "candidate_users.create", "candidate_users.edit", "candidate_users.delete",
    "notifications.view", "notifications.send",
    "courses.view", "courses.create", "courses.edit", "courses.delete",
    "programs.view", "programs.create", "programs.edit", "programs.delete",
    "batches.view", "batches.create", "batches.edit", "batches.delete",
    "centers.view", "centers.create", "centers.edit", "centers.delete",
    "trainers.view", "trainers.create", "trainers.edit", "trainers.assign", "trainers.delete", "trainers.manage", "trainers.status.manage",
    "schedule.view", "schedule.create", "schedule.edit", "schedule.delete",
    "attendance.view", "attendance.manage",
    "assessments.view", "assessments.create", "assessments.edit", "assessments.delete", "assessments.publish",
    "certifications.view", "certifications.create", "certifications.edit", "certifications.delete",
    "readiness.view", "readiness.manage",
    "lms.view", "lms.create", "lms.edit", "lms.manage",
    "quizzes.view", "quizzes.create", "quizzes.edit", "quizzes.delete", "quizzes.publish",
    "payments.view", "payments.manage",
    "support.view", "support.manage",
    "logs.view",
    "settings.view", "settings.edit", "settings.manage",
    "email_templates.view", "email_templates.edit",
    "course_content.view", "course_content.create", "course_content.edit", "course_content.delete",
    "learning_resources.view", "learning_resources.create", "learning_resources.edit", "learning_resources.delete", "learning_resources.assign",
    "course_content_folder.view", "course_content_folder.create", "course_content_folder.edit", "course_content_folder.delete",
    "assessment_pool.view", "assessment_pool.create", "assessment_pool.edit", "assessment_pool.delete", "assessment_pool.publish",
    "assessment_reviews.view", "assessment_reviews.manage", "assessment_reviews.grade",
    "batch_content.view", "batch_content.assign", "batch_content.remove",
    "curriculum.view", "curriculum.create", "curriculum.edit", "curriculum.delete", "curriculum.publish",
  ],
  TRAINER: [
    "dashboard.view",
    "auth.login",
    "sessions.view", "sessions.manage",
    "courses.view",
    "programs.view",
    "batches.view",
    "trainers.view",
    "schedule.view", "schedule.create", "schedule.edit", "schedule.delete",
    "attendance.view", "attendance.manage",
    "assessments.view", "assessments.create", "assessments.edit",
    "certifications.view",
    "readiness.view",
    "lms.view",
    "quizzes.view", "quizzes.create", "quizzes.edit",
    "course_content.view",
    "learning_resources.view",
    "course_content_folder.view",
    "assessment_pool.view",
    "assessment_reviews.view", "assessment_reviews.manage", "assessment_reviews.grade",
    "batch_content.view", "batch_content.assign", "batch_content.remove",
    "curriculum.view",
  ],
  CONTENT_MANAGER: [
    "dashboard.view",
    "auth.login",
    "sessions.view", "sessions.manage",
    "courses.view", "courses.create", "courses.edit", "courses.delete",
    "programs.view", "programs.create", "programs.edit", "programs.delete",
    "assessments.view",
    "lms.view", "lms.create", "lms.edit", "lms.manage",
    "quizzes.view", "quizzes.create", "quizzes.edit", "quizzes.delete", "quizzes.publish",
    "email_templates.view", "email_templates.create", "email_templates.edit", "email_templates.delete",
    "course_content.view", "course_content.create", "course_content.edit", "course_content.delete",
    "learning_resources.view", "learning_resources.create", "learning_resources.edit", "learning_resources.delete", "learning_resources.assign",
    "course_content_folder.view", "course_content_folder.create", "course_content_folder.edit", "course_content_folder.delete",
    "assessment_pool.view", "assessment_pool.create", "assessment_pool.edit", "assessment_pool.delete", "assessment_pool.publish",
    "batch_content.view", "batch_content.assign", "batch_content.remove",
    "curriculum.view", "curriculum.create", "curriculum.edit", "curriculum.delete", "curriculum.publish",
  ],
  SUPPORT_USER: [
    "dashboard.view",
    "auth.login",
    "sessions.view", "sessions.manage",
    "users.view",
    "notifications.view",
    "support.view", "support.manage",
  ],
};
